apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: default
data:
  config.yaml: |
    services:
      - name: policy-service
        url: http://localhost:8181/v1
    labels:
      app: "opa"
    discovery:
      name: /policy
      prefix: config
    bundle:
      name: example
      service: policy-service
      resource: example/bundle.tar.gz
    plugins:
      - name: http.send
        service: policy-service
