apiVersion: v1
kind: Service
metadata:
  name: my-cool-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  selector:
    app: my-cool-service
